### ISSUE TITLE
What is the reason for not considering using the M5 dataset

### ISSUE THREAD

**Issue by isCopyman** [decisionintelligence/TFB#10]
The paper introduced the M3 and M4 datasets, but did not consider the M5 dataset. What is the reason for this consideration.

**Comment by qiu69** [comment]
Thank you for your attention and questions！ Because M5 is mainly from the sales field, and we already include many sales datasets, we did not consider M5. If you need to evaluate M5, we will consider incorporating it into TFB in the future. This requirement has been added to our plan but has a low priority.
